# manifest:
#   remotes:
#     - name: zmkfirmware
#       url-base: https://github.com/zmkfirmware
#   projects:
#     - name: zmk
#       remote: zmkfirmware
#       revision: main
#       import: app/west.yml
#   self:
#     path: config

manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: bcat
      url-base: https://github.com/bcat
  projects:
    - name: zmk
      remote: bcat
      revision: tri_layer
      import: app/west.yml
  self:
    path: config
